fm_elfinder:
    instances:
        default:
            editor: ckeditor
            locale: '%locale%'
            cors_support: true
            relative_path: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads